import type { Item } from '../types/item';

export const mockItems: Item[] = [
  {
    id: '1',
    title: 'HP Prime Graphing Calculator',
    description: 'Perfect for engineering students taking advanced math or engineering subjects. Lending for up to 2 weeks.',
    category: 'ACADEMICS',
    subcategory: 'GRAPHING_CALCULATOR',
    condition: 'EXCELLENT',
    preferredTransaction: 'HIRAM',
    isAvailable: true,
    owner: 'Maria Clara',
    ownerId: 'user-maria-clara',
    createdAt: new Date('2026-05-15'),
    image: 'https://images.unsplash.com/photo-1594818821901-b68a52862c64?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '133900000',
    barangayCode: '133901001'
  },
  {
    id: '2',
    title: 'Professional Tripod & Ring Light',
    description: 'Used for journalism or broadcasting projects. Complete set with carrying bag.',
    category: 'ELECTRONICS',
    subcategory: 'LAPTOP_ACCESSORIES',
    condition: 'GOOD',
    preferredTransaction: 'TRADE',
    isAvailable: true,
    owner: 'Juan Dela Cruz',
    ownerId: 'user-juan',
    createdAt: new Date('2026-05-17'),
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '137607000',
    barangayCode: '137607020'
  },
  {
    id: '3',
    title: 'Rotring Drafting Board (A3)',
    description: 'Heavy duty drawing board for architecture plates. Well-maintained T-square included.',
    category: 'CREATIVE',
    subcategory: 'DRAWING_BOARDS',
    condition: 'EXCELLENT',
    preferredTransaction: 'HIRAM',
    isAvailable: true,
    owner: 'Isagani Santos',
    ownerId: 'user-isagani',
    createdAt: new Date('2026-05-18'),
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '133900000',
    barangayCode: '133901002'
  },
  {
    id: '4',
    title: 'Chemistry Laboratory Manual',
    description: 'Clean lab manual with no markings. Essential study guide for general chemistry courses.',
    category: 'ACADEMICS',
    subcategory: 'REFERENCE_MATERIALS',
    condition: 'EXCELLENT',
    preferredTransaction: 'TRADE',
    isAvailable: true,
    owner: 'Ariel Roxas',
    ownerId: 'user-ariel',
    createdAt: new Date('2026-05-18'),
    image: undefined,
    regionCode: '130000000',
    cityCode: '137607000',
    barangayCode: '137607018'
  },
  {
    id: '5',
    title: 'Wanted: Drafting Table & T-Square',
    description: 'Looking for a drafting table or T-square for the upcoming architectural design plates. Urgent request.',
    category: 'CREATIVE',
    subcategory: 'DRAWING_BOARDS',
    condition: 'GOOD',
    preferredTransaction: 'REQUEST',
    isAvailable: true,
    owner: 'Patricia Reyes',
    ownerId: 'user-patricia',
    createdAt: new Date('2026-05-19'),
    image: undefined,
    regionCode: '130000000',
    cityCode: '133900000',
    barangayCode: '133901001'
  },
  {
    id: '6',
    title: 'Casio fx-991ES Plus Scientific Calculator',
    description: 'Excellent condition, great for engineering and science subjects. Includes original protective case.',
    category: 'ACADEMICS',
    subcategory: 'SCIENTIFIC_CALCULATOR',
    condition: 'EXCELLENT',
    preferredTransaction: 'HIRAM',
    isAvailable: true,
    owner: 'Maria Clara',
    ownerId: 'user-maria-clara',
    createdAt: new Date('2026-05-14'),
    image: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '133900000',
    barangayCode: '133901001'
  },
  {
    id: '7',
    title: 'Laptop Stand & External Keyboard',
    description: 'Adjustable aluminum laptop stand with ergonomic wireless keyboard. Perfect for online classes and work.',
    category: 'ELECTRONICS',
    subcategory: 'LAPTOP_ACCESSORIES',
    condition: 'EXCELLENT',
    preferredTransaction: 'HIRAM',
    isAvailable: true,
    owner: 'Juan Dela Cruz',
    ownerId: 'user-juan',
    createdAt: new Date('2026-05-16'),
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '137607000',
    barangayCode: '137607020'
  },
  {
    id: '8',
    title: 'Design Thinking Toolkit & Resources',
    description: 'Complete set of design thinking materials, color palette tools, and reference guides for creative projects.',
    category: 'CREATIVE',
    subcategory: 'DESIGN_MATERIALS',
    condition: 'EXCELLENT',
    preferredTransaction: 'TRADE',
    isAvailable: true,
    owner: 'Isagani Santos',
    ownerId: 'user-isagani',
    createdAt: new Date('2026-05-13'),
    image: 'https://images.unsplash.com/photo-1541961017774-22018e1fbf32?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '133900000',
    barangayCode: '133901002'
  },
  {
    id: '9',
    title: 'Biology Textbook & Lab Manual Set',
    description: 'Complete set for biology courses including lab manual with detailed illustrations. Very helpful for understanding concepts.',
    category: 'ACADEMICS',
    subcategory: 'REFERENCE_MATERIALS',
    condition: 'EXCELLENT',
    preferredTransaction: 'HIRAM',
    isAvailable: true,
    owner: 'Ariel Roxas',
    ownerId: 'user-ariel',
    createdAt: new Date('2026-05-17'),
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '137607000',
    barangayCode: '137607018'
  },
  {
    id: '10',
    title: 'Photography Lighting Kit',
    description: 'Professional lighting setup with three stands, softboxes, and umbrella reflectors. Perfect for photography projects.',
    category: 'ELECTRONICS',
    subcategory: 'PHOTOGRAPHY_EQUIPMENT',
    condition: 'GOOD',
    preferredTransaction: 'TRADE',
    isAvailable: true,
    owner: 'Maria Clara',
    ownerId: 'user-maria-clara',
    createdAt: new Date('2026-05-12'),
    image: 'https://images.unsplash.com/photo-1606933248051-5ce98adc62af?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '133900000',
    barangayCode: '133901001'
  },
  {
    id: '11',
    title: 'Engineering Drawing Set & Compass Collection',
    description: 'Complete set with precision compass, divider, protractor, and scale rulers. Essential for technical drawing courses.',
    category: 'CREATIVE',
    subcategory: 'DRAWING_TOOLS',
    condition: 'EXCELLENT',
    preferredTransaction: 'HIRAM',
    isAvailable: true,
    owner: 'Juan Dela Cruz',
    ownerId: 'user-juan',
    createdAt: new Date('2026-05-11'),
    image: 'https://images.unsplash.com/photo-1534080564897-61ee3645fdc0?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '137607000',
    barangayCode: '137607020'
  },
  {
    id: '12',
    title: 'Portable Projector & Screen',
    description: 'Compact but powerful projector ideal for presentations and group study. Includes carrying bag and HDMI cables.',
    category: 'ELECTRONICS',
    subcategory: 'PRESENTATION_EQUIPMENT',
    condition: 'EXCELLENT',
    preferredTransaction: 'HIRAM',
    isAvailable: true,
    owner: 'Isagani Santos',
    ownerId: 'user-isagani',
    createdAt: new Date('2026-05-10'),
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60',
    regionCode: '130000000',
    cityCode: '133900000',
    barangayCode: '133901002'
  }
];
